'use strict';

module.exports = Object.freeze({
    SUCCESS: "Action is successfull",
    ERROR: "Have a error",


    // UPLOAD 
    UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
    UPLOAD_FAIL: "UPLOAD_FAIL",
    DELETE_FAIL: "DELETE_FAIL",
    DELETE_SUCCESS: "DELETE_SUCCESS",


    // USERs 
    USER_EXIST_NAME: "USER_EXIST_NAME",
    USER_USERNAME_NOT_EXIST: "USERNAME_NOT_EXIST",
    USER_EMAIL_NOT_EXIST: "EMAIL_NOT_EXIST",
    USER_NOT_ACTIVE: "USER_NOT_ACTIVE",
    USER_USERNAME_EXIST: "USER_USERNAME_EXIST",
    USER_FOUND: "USER_FOUNDED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_TYPE_INVALID: "USER_TYPE_INVALID",
    USER_NOT_AVAILABLE: "USER_NOT_AVAILABLE",
    USER_ID_NOT_FOUND: "USER_ID_NOT_FOUND",
    USER_MAIL_NOT_FOUND: "USER_MAIL_NOT_FOUND",
    USER_MAIL_EXIST: "USER_MAIL_EXIST",
    USER_PHONE_EXIST: "USER_PHONE_EXIST",
    USER_MAIL_NOT_EXIST: "USER_MAIL_NOT_EXIST",
    USER_PASS_INVALID: "USER_PASSWORD_INVALID",
    USER_CONFIRMPASS_INVALID: "CONFIRM_PASS_INVALID",
    USER_PASS_EXIST: "USER_PASSWORD_EXIST",
    USER_CREATE_SUSSCESS: "USER_CREATE_SUSSCESS",
    USER_CREATE_FAIL: "USER_CREATE_FAIL",
    USER_UPDATE_SUSSCESS: "USER_UPDATE_SUSSCESS",
    USER_UPDATE_FAIL: "USER_UPDATE_FAIL",
    USER_RESTORE_SUSSCESS: "USER_RESTORE_SUSSCESS",
    USER_RESTORE_FAIL: "USER_RESTORE_FAIL ",
    USER_MAIL_REQUIRED: "TRY_ANOTHER_EMAIL",
    USER_DELETED: "USER_DELETED",
    USER_DELETE_FAIL: "USER_DELETE_FAIL",
    USER_LOGIN_SUSSCESS: "USER_LOGIN_SUSSCESS",
    USER_EMAIL_SENDED: "USER_EMAIL_SENDED",
    EMAIL_DATE_EXPIRED: "EMAIL_DATE_EXPIRED",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_DOES_NOT_HAVE_A_WALLET: "USER_DOES_NOT_HAVE_A_WALLET",
    USER_MAIL_EXIST_OR_PHONE: "USER_MAIL_EXIST_OR_PHONE",
    USER_HAD_EXIST_BUT_NOT_ACTIVE: "USER_HAD_EXIST_BUT_NOT_ACTIVE",
    USER_EXIST: "USER_EXIST",
    USER_VERIFY_DATE_EXPIRED: "USER_VERIFY_DATE_EXPIRED",



    //RELATIVE
    WHEEL_USER_EXIST: "WHEEL_USER_EXIST",
    WHEEL_ROTATION_EXIST: "WHEEL_ROTATION_EXIST",
    RELATIVE_NOT_FOUND: "RELATIVE_NOT_FOUND",


    //You
    YOU_ARE_NOT_OWNER_TEAM: "YOU_ARE_NOT_OWNER_TEAM",
    YOU_ARE_NOT_OWNER_POST: "YOU_ARE_NOT_OWNER_POST",
    YOU_ARE_ALREADY_REQUEST: "YOU_ARE_ALREADY_REQUEST",


    //TOURNAMENT
    TOURNAMENT_NAME_EXIST: "TOURNAMENT_NAME_EXIST",
    TOURNAMENT_NOT_FOUND: "TOURNAMENT_NOT_FOUND",


})